// Mocks generated by Mockito 5.4.6 from annotations
// in fpv_fic/test/controllers/founds_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpv_fic/domain/enity/fondo.dart' as _i5;
import 'package:fpv_fic/domain/enity/transaction.dart' as _i6;
import 'package:fpv_fic/domain/enity/usuario.dart' as _i2;
import 'package:fpv_fic/domain/repository/auth_repository.dart' as _i7;
import 'package:fpv_fic/domain/repository/fondos_repository.dart' as _i3;
import 'package:fpv_fic/domain/repository/sesion_repository.dart' as _i8;
import 'package:fpv_fic/domain/use_case/auth/login_user_use_case.dart' as _i9;
import 'package:fpv_fic/domain/use_case/auth/logout_use_case.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUsuarioModel_0 extends _i1.SmartFake implements _i2.UsuarioModel {
  _FakeUsuarioModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FondosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFondosRepository extends _i1.Mock implements _i3.FondosRepository {
  MockFondosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.FondoModel>> getFondos() =>
      (super.noSuchMethod(
            Invocation.method(#getFondos, []),
            returnValue: _i4.Future<List<_i5.FondoModel>>.value(
              <_i5.FondoModel>[],
            ),
          )
          as _i4.Future<List<_i5.FondoModel>>);

  @override
  _i4.Future<void> suscribeFondo(
    String? fondoId,
    _i6.MetodoNotificacion? metodo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#suscribeFondo, [fondoId, metodo]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unsuscribeFondo(String? fondoId) =>
      (super.noSuchMethod(
            Invocation.method(#unsuscribeFondo, [fondoId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.TransaccionModel>> getTransactions(String? fondoId) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, [fondoId]),
            returnValue: _i4.Future<List<_i6.TransaccionModel>>.value(
              <_i6.TransaccionModel>[],
            ),
          )
          as _i4.Future<List<_i6.TransaccionModel>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<(_i2.UsuarioModel, String?)> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<(_i2.UsuarioModel, String?)>.value((
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#login, [email, password]),
              ),
              null,
            )),
          )
          as _i4.Future<(_i2.UsuarioModel, String?)>);

  @override
  void logout() => super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.UsuarioModel getUsuarioActivo() =>
      (super.noSuchMethod(
            Invocation.method(#getUsuarioActivo, []),
            returnValue: _FakeUsuarioModel_0(
              this,
              Invocation.method(#getUsuarioActivo, []),
            ),
          )
          as _i2.UsuarioModel);

  @override
  _i2.UsuarioModel getUsuarioById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUsuarioById, [id]),
            returnValue: _FakeUsuarioModel_0(
              this,
              Invocation.method(#getUsuarioById, [id]),
            ),
          )
          as _i2.UsuarioModel);

  @override
  _i4.Future<void> updateSaldo(double? d) =>
      (super.noSuchMethod(
            Invocation.method(#updateSaldo, [d]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SesionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSesionRepository extends _i1.Mock implements _i8.SesionRepository {
  MockSesionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveSession(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [LoginUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUserUseCase extends _i1.Mock implements _i9.LoginUserUseCase {
  MockLoginUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<(_i2.UsuarioModel, String?)> call(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email, password]),
            returnValue: _i4.Future<(_i2.UsuarioModel, String?)>.value((
              _FakeUsuarioModel_0(
                this,
                Invocation.method(#call, [email, password]),
              ),
              null,
            )),
          )
          as _i4.Future<(_i2.UsuarioModel, String?)>);
}

/// A class which mocks [LogoutUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUserUseCase extends _i1.Mock implements _i10.LogoutUserUseCase {
  MockLogoutUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call() => super.noSuchMethod(
    Invocation.method(#call, []),
    returnValueForMissingStub: null,
  );
}
